version: "3.9"
services:
  payments-server:
    build: .
    volumes:
      - ./src:/app/src
      - ./test:/app/test
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - MNEMONIC=${MNEMONIC}
      - INFURA_API_KEY=${INFURA_API_KEY}
