version: "3.9"
services:
  payments-server:
    build: .
    volumes:
      - ./src:/app/src
      - ./test:/app/test
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - MNEMONIC=${MNEMONIC}
      - INFURA_API_KEY=${INFURA_API_KEY}
      - ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}
      - DATABASE_URL=postgresql://test:test@postgres:5432/test
    depends_on:
      - postgres
  postgres:
    image: postgres:14.2
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables on init
      - ./src/postgres/sql/tables.sql:/docker-entrypoint-initdb.d/tables.sql
    ports:
      - "5438:5432"
