CREATE TABLE WALLET (
    ID              SERIAL PRIMARY KEY,
    USER_ID         VARCHAR(5000)  NOT NULL UNIQUE,
    PRIVATE_KEY     VARCHAR(1000) NOT NULL,
    ADDRESS         VARCHAR(1000) NOT NULL
);

CREATE TABLE TRANSACTION (
    ID                VARCHAR(1000) NOT NULL,
    USER_ID           VARCHAR(5000) NOT NULL,
    RECEIVER_ADDRESS  VARCHAR(1000) NOT NULL,
    SENDER_ADDRESS    VARCHAR(1000) NOT NULL,
    AMOUNT            float8 NOT NULL,
    DAY               int4 NOT NULL,
    MONTH             int4 NOT NULL,
    YEAR              int4 NOT NULL,
    CONSTRAINT deposit_pkey PRIMARY KEY (ID)
);
