CREATE TABLE WALLET (
    ID              SERIAL PRIMARY KEY,
    USER_ID         VARCHAR(5000)  NOT NULL UNIQUE,
    PRIVATE_KEY     VARCHAR(1000) NOT NULL,
    ADDRESS         VARCHAR(1000) NOT NULL
);

CREATE TABLE DEPOSIT (
    ID                VARCHAR(1000) NOT NULL,
    WALLET_ID         VARCHAR(5000) NOT NULL,
    AMOUNT            float8 NOT NULL,
    MONTH             int4 NOT NULL,
    YEAR              int4 NOT NULL,
    CONSTRAINT deposit_pkey PRIMARY KEY (ID)
);
